[package]
name    = "hn-reader-rs"
version = "0.1.0"
authors = ["Jacob Killelea <jkillelea@protonmail.ch>"]

[dependencies]
url     = "*"
reqwest = "*"
serde_json = "*"

[dependencies.gtk]
version = "*"
features = ["v3_10"] # get ListBox in scope
